# Generated by Django 5.2.2 on 2025-06-10 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_text', models.TextField()),
                ('time_taken_seconds', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('wpm', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
